spring:
  profiles:
#    active: topic
  #    第六课
   #active: rpc


#    第五课
#    active: topic

#    第四课
     #     active: routing

    #    第三课
    #active: exchange
    #    第二课
#       active: work
    #    第一课
    active: hello
  rabbitmq:
    host: 113.140.81.69
