#https://github.com/aliyun/aliyun-oss-java-sdk
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI4FinQH34oRXWMDY4vLdD # 访问身份验证中用到用户标识
    accessKeySecret: jktatW2goeDUFzV7qJp3YxgY2xmUyF # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: ice-temp # oss的存储空间
    #使用了netapp做了网络映射
    callback: http://t38i78.natappfree.cc/aliyun/oss/callback # 文件上传成功后的回调地址
    policy:
      expire: 300 # 签名有效期(S)
